# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: af218da25cd5b981c476907362a2e60301c9b8f262df58a16a9c3d91cfde2b2c31ef17d2c24c53d37c14401845009ca6c9f5821bffa4e0a0eaf65798d845cbc0

test:
  secret_key_base: 9d51e4af5c7aeba1c26efa60a8d6e2795fb793cadbb29bd044dd74a10d6916d118459cfc2cf3e9239696867792ac2c6a967914f66b1dfc4c5459638276a9b8f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 7a05856e83ccf7cc79492c49e81fd98155d25343970979e00191cf27b8839dcca413fb44ef294031bda9466825a4ee2a9ef456c22a41a17c9cd1683bd9ed07f5
